#!/bin/sh

REQUIREMENTS="/sbin/ip /usr/bin/slirp-fullbolt"
for R in $REQUIREMENTS; do
	if [ ! -x "$R" ]; then
		echo "Requirement $R not found. Aborting."
		exit 1
	fi
done

if [ "$2" ]; then
	shift
	echo "Extraneous arguments: $* Try to enclose them within quotes?"
	exit 255
fi

# backwards compatability...
if [ ! -z "$HOST_IP" ]; then
	echo "DEPRECATED USE OF ENVIRONMENT VARIABLE, CONSIDER SWITCHING TO SLIRP_HOST AS SOON AS POSSIBLE."
	SLIRP_HOST="$HOST_IP"
fi

if [ -n "$SLIRP_PORTS" ] && [ "x$SLIRP_HOST" = "x" ]; then
  echo "The HOST_IP must be defined to setup redirects with SLIRP_PORTS."
  exit 255
fi

LOGDIR="/tmp/log.$$"
mkdir "$LOGDIR"

if [ "$1" ]; then
	CMD="$1"
	STDIN="/dev/null"
	STDOUT="/dev/null"
	STDERR="/dev/null"
	touch "$LOGDIR/output"
	if [ "$VERBOSE" = 1 ]; then
		tail -f "$LOGDIR/output" &
	fi
	TAILPID="$!"
	trap '' TERM
else
	CMD="/bin/bash"
	STDIN="/dev/stdin"
	STDOUT="/dev/stdout"
	STDERR="/dev/stderr"
	TAILPID=""
fi

cat "/etc/resolv.conf" > "$LOGDIR/resolv.conf"

echo "$CMD" > $LOGDIR/cmd

chmod +x "$INITDIR/uml"

INITDIR="$(readlink --canonicalize "$(dirname "$0")")"
"$INITDIR/uml" quiet rootfstype="hostfs" rootflags="/" ro \
	mem="$(grep "MemTotal" "/proc/meminfo" | awk '{ print $2 }')K" \
	eth0="slirp,,$INITDIR/slirp-wrapper" \
	init="$INITDIR/init ""$*""" LOGDIR="$LOGDIR" \
	<"$STDIN" >"$STDOUT" 2>"$STDERR"

# Due to a weird behavior of usermodelinux, sometimes it will kill the
# whole process group, and we won't have to kill tail. Duh.
if [ "$TAILPID" ] && [ -d /proc/$TAILPID ]; then
	/bin/kill "$TAILPID" >"/dev/null" 2>"/dev/null"
fi

STATUS=""
[ -f "$LOGDIR/status" ] && STATUS="$(cat "$LOGDIR/status")"
[ "$DEBUG" ] || rm -rf "$LOGDIR"
[ "$STATUS" ] && exit "$STATUS"
exit 255
